--CREATE TRIGGER hashEditInsertTrigger BEFORE INSERT ON contests FOR EACH ROW SET new.editHash = TO_BASE64(RANDOM_BYTES(32));

CREATE TRIGGER hashEditUpdateTrigger BEFORE UPDATE ON contests FOR EACH ROW SET new.editHash = SHA2(TO_BASE64(RANDOM_BYTES(32)), 256);
CREATE TRIGGER hashEditInsertTrigger BEFORE INSERT ON contests FOR EACH ROW SET new.editHash = SHA2(TO_BASE64(RANDOM_BYTES(32)), 256);

INSERT INTO contestsdb.categories (id, name) VALUES (1, 'Konkursy muzyczne');
INSERT INTO contestsdb.categories (id, name) VALUES (2, 'Konkursy internetowe');
INSERT INTO contestsdb.categories (id, name) VALUES (3, 'Konkursy SMS');
INSERT INTO contestsdb.categories (id, name) VALUES (4, 'Konkursy fotograficzne');
INSERT INTO contestsdb.categories (id, name) VALUES (5, 'Konkursy lokalne');
INSERT INTO contestsdb.categories (id, name) VALUES (6, 'Konkursy kulinarne');
INSERT INTO contestsdb.categories (id, name) VALUES (7, 'Inne konkursy');
INSERT INTO contestsdb.categories (id, name) VALUES (8, 'Konkursy na Facebooku');

INSERT INTO contestsdb.tags (id, name) VALUES (1, 'książki');
INSERT INTO contestsdb.tags (id, name) VALUES (2, 'kosmetyki');
INSERT INTO contestsdb.tags (id, name) VALUES (3, 'gadżety');
INSERT INTO contestsdb.tags (id, name) VALUES (4, 'pieniężne');
INSERT INTO contestsdb.tags (id, name) VALUES (5, 'alkohol');
INSERT INTO contestsdb.tags (id, name) VALUES (6, 'bilety');
INSERT INTO contestsdb.tags (id, name) VALUES (7, 'samochód');
INSERT INTO contestsdb.tags (id, name) VALUES (8, 'bony');
INSERT INTO contestsdb.tags (id, name) VALUES (9, 'zegarek');

INSERT INTO contestsdb.reward_type (id, name) VALUES (1, 'Elektronika');
INSERT INTO contestsdb.reward_type (id, name) VALUES (2, 'Wycieczki');
INSERT INTO contestsdb.reward_type (id, name) VALUES (3, 'Gadżety');
INSERT INTO contestsdb.reward_type (id, name) VALUES (4, 'Kosmetyki');
INSERT INTO contestsdb.reward_type (id, name) VALUES (5, 'Pieniężne');
INSERT INTO contestsdb.reward_type (id, name) VALUES (6, 'Odzież');
INSERT INTO contestsdb.reward_type (id, name) VALUES (7, 'Inne');
INSERT INTO contestsdb.reward_type (id, name) VALUES (8, 'Dla dzieci');
--
--ok
--INSERT INTO contestsdb.contests (id, contest_link, description, end_date, image, organizer, reward_description, rules_link, short_description, start_date, title) VALUES (null, 'https://www.loteria.dajcosodsiebie.pl/#zasady', '1. Kup dowolne produkty Tymbark za minimum 6 zł spośród soków, nektarów i napojów od 0,2l do 0,3l) i zachowaj paragon', '2018-12-30 22:59:00', '/upload-dir/BrXBay18-dajcosodsiebietymbark.jpg', 'Tymark', '– 1x samochód Toyota C-HR – 210x bon podarunkowy YES o wartości 200 zł (codziennie 5 nagród)', 'https://www.loteria.dajcosodsiebie.pl/regulaminy/Regulamin%20loterii%20Tymbark.pdf', 'Do wygrania Toyota C-HR oraz bony upominkowe YES o wartości 200 zł!', '2018-11-18 23:00:00', 'ŚWIĄTECZNA LOTERIA TYMBARK DAJ COŚ OD SIEBIE');
INSERT INTO contestsdb.contests (id, accepted, contest_link, description, end_date, image, organizer, reward_description, rules_link, short_description, start_date, title) VALUES (1, true, 'https://www.loteria.dajcosodsiebie.pl/#zasady', '1. Kup dowolne produkty Tymbark za minimum 6 zł spośród soków, nektarów i napojów od 0,2l do 0,3l) i zachowaj paragon', '2018-12-30 22:59:00', '/upload-dir/BrXBay18-dajcosodsiebietymbark.jpg', 'Tymark', '– 1x samochód Toyota C-HR – 210x bon podarunkowy YES o wartości 200 zł (codziennie 5 nagród)', 'https://www.loteria.dajcosodsiebie.pl/regulaminy/Regulamin%20loterii%20Tymbark.pdf', 'Do wygrania Toyota C-HR oraz bony upominkowe YES o wartości 200 zł!', '2018-11-18 23:00:00', 'ŚWIĄTECZNA LOTERIA TYMBARK DAJ COŚ OD SIEBIE');
INSERT INTO contestsdb.contests (id, accepted,contest_link, description, end_date, image, organizer, reward_description, rules_link, short_description, start_date, title) VALUES (2,true, 'https://www.loteria.dajcosodsiebie.pl/#zasady', '1. Kup dowolne produkty Tymbark za minimum 6 zł spośród soków, nektarów i napojów od 0,2l do 0,3l) i zachowaj paragon', '2018-12-30 22:59:00', '/upload-dir/HzSLTMsm-pantenec4.jpg', 'Tymark', '– 1x samochód Toyota C-HR – 210x bon podarunkowy YES o wartości 200 zł (codziennie 5 nagród)', 'https://www.loteria.dajcosodsiebie.pl/regulaminy/Regulamin%20loterii%20Tymbark.pdf', 'Do wygrania Toyota C-HR oraz bony upominkowe YES o wartości 200 zł!', '2018-11-18 23:00:00', 'ŚWIĄTECZNA LOTERIA TYMBARK DAJ COŚ OD SIEBIE');
INSERT INTO contestsdb.contests (id, accepted,contest_link, description, end_date, image, organizer, reward_description, rules_link, short_description, start_date, title) VALUES (3, true,'https://www.loteria.dajcosodsiebie.pl/#zasady', '1. Kup dowolne produkty Tymbark za minimum 6 zł spośród soków, nektarów i napojów od 0,2l do 0,3l) i zachowaj paragon', '2018-12-30 22:59:00', '/upload-dir/wLH4qu08-topazgwiazdka.jpg', 'Tymark', '– 1x samochód Toyota C-HR – 210x bon podarunkowy YES o wartości 200 zł (codziennie 5 nagród)', 'https://www.loteria.dajcosodsiebie.pl/regulaminy/Regulamin%20loterii%20Tymbark.pdf', 'Do wygrania Toyota C-HR oraz bony upominkowe YES o wartości 200 zł!', '2018-11-18 23:00:00', 'ŚWIĄTECZNA LOTERIA TYMBARK DAJ COŚ OD SIEBIE');
INSERT INTO contestsdb.contests (id, accepted,contest_link, description, end_date, image, organizer, reward_description, rules_link, short_description, start_date, title) VALUES (4, true,'https://www.loteria.dajcosodsiebie.pl/#zasady', '1. Kup dowolne produkty Tymbark za minimum 6 zł spośród soków, nektarów i napojów od 0,2l do 0,3l) i zachowaj paragon', '2018-12-30 22:59:00', '/upload-dir/Y0RtwEkE-bakallanditm.jpg', 'Tymark', '– 1x samochód Toyota C-HR – 210x bon podarunkowy YES o wartości 200 zł (codziennie 5 nagród)', 'https://www.loteria.dajcosodsiebie.pl/regulaminy/Regulamin%20loterii%20Tymbark.pdf', 'Do wygrania Toyota C-HR oraz bony upominkowe YES o wartości 200 zł!', '2018-11-18 23:00:00', 'ŚWIĄTECZNA LOTERIA TYMBARK DAJ COŚ OD SIEBIE');
INSERT INTO contestsdb.contests (id, accepted,contest_link, description, end_date, image, organizer, reward_description, rules_link, short_description, start_date, title) VALUES (5,true, 'https://www.loteria.dajcosodsiebie.pl/#zasady', '1. Kup dowolne produkty Tymbark za minimum 6 zł spośród soków, nektarów i napojów od 0,2l do 0,3l) i zachowaj paragon', '2018-12-30 22:59:00', '/upload-dir/BrXBay18-dajcosodsiebietymbark.jpg', 'Tymark', '– 1x samochód Toyota C-HR – 210x bon podarunkowy YES o wartości 200 zł (codziennie 5 nagród)', 'https://www.loteria.dajcosodsiebie.pl/regulaminy/Regulamin%20loterii%20Tymbark.pdf', 'Do wygrania Toyota C-HR oraz bony upominkowe YES o wartości 200 zł!', '2018-11-18 23:00:00', 'ŚWIĄTECZNA LOTERIA TYMBARK DAJ COŚ OD SIEBIE');
INSERT INTO contestsdb.contests (id, accepted,contest_link, description, end_date, image, organizer, reward_description, rules_link, short_description, start_date, title) VALUES (6,true, 'https://www.loteria.dajcosodsiebie.pl/#zasady', '1. Kup dowolne produkty Tymbark za minimum 6 zł spośród soków, nektarów i napojów od 0,2l do 0,3l) i zachowaj paragon', '2018-12-30 22:59:00', '/upload-dir/HzSLTMsm-pantenec4.jpg', 'Tymark', '– 1x samochód Toyota C-HR – 210x bon podarunkowy YES o wartości 200 zł (codziennie 5 nagród)', 'https://www.loteria.dajcosodsiebie.pl/regulaminy/Regulamin%20loterii%20Tymbark.pdf', 'Do wygrania Toyota C-HR oraz bony upominkowe YES o wartości 200 zł!', '2018-11-18 23:00:00', 'ŚWIĄTECZNA LOTERIA TYMBARK DAJ COŚ OD SIEBIE');
INSERT INTO contestsdb.contests (id, accepted,contest_link, description, end_date, image, organizer, reward_description, rules_link, short_description, start_date, title) VALUES (7,true, 'https://www.loteria.dajcosodsiebie.pl/#zasady', '1. Kup dowolne produkty Tymbark za minimum 6 zł spośród soków, nektarów i napojów od 0,2l do 0,3l) i zachowaj paragon', '2018-12-30 22:59:00', '/upload-dir/wLH4qu08-topazgwiazdka.jpg', 'Tymark', '– 1x samochód Toyota C-HR – 210x bon podarunkowy YES o wartości 200 zł (codziennie 5 nagród)', 'https://www.loteria.dajcosodsiebie.pl/regulaminy/Regulamin%20loterii%20Tymbark.pdf', 'Do wygrania Toyota C-HR oraz bony upominkowe YES o wartości 200 zł!', '2018-11-18 23:00:00', 'ŚWIĄTECZNA LOTERIA TYMBARK DAJ COŚ OD SIEBIE');
INSERT INTO contestsdb.contests (id, accepted,contest_link, description, end_date, image, organizer, reward_description, rules_link, short_description, start_date, title) VALUES (8, true,'https://www.loteria.dajcosodsiebie.pl/#zasady', '1. Kup dowolne produkty Tymbark za minimum 6 zł spośród soków, nektarów i napojów od 0,2l do 0,3l) i zachowaj paragon', '2018-12-30 22:59:00', '/upload-dir/Y0RtwEkE-bakallanditm.jpg', 'Tymark', '– 1x samochód Toyota C-HR – 210x bon podarunkowy YES o wartości 200 zł (codziennie 5 nagród)', 'https://www.loteria.dajcosodsiebie.pl/regulaminy/Regulamin%20loterii%20Tymbark.pdf', 'Do wygrania Toyota C-HR oraz bony upominkowe YES o wartości 200 zł!', '2018-11-18 23:00:00', 'ŚWIĄTECZNA LOTERIA TYMBARK DAJ COŚ OD SIEBIE');
INSERT INTO contestsdb.contests (id, accepted,contest_link, description, end_date, image, organizer, reward_description, rules_link, short_description, start_date, title) VALUES (9, true,'https://www.loteria.dajcosodsiebie.pl/#zasady', '1. Kup dowolne produkty Tymbark za minimum 6 zł spośród soków, nektarów i napojów od 0,2l do 0,3l) i zachowaj paragon', '2018-12-30 22:59:00', '/upload-dir/BrXBay18-dajcosodsiebietymbark.jpg', 'Tymark', '– 1x samochód Toyota C-HR – 210x bon podarunkowy YES o wartości 200 zł (codziennie 5 nagród)', 'https://www.loteria.dajcosodsiebie.pl/regulaminy/Regulamin%20loterii%20Tymbark.pdf', 'Do wygrania Toyota C-HR oraz bony upominkowe YES o wartości 200 zł!', '2018-11-18 23:00:00', 'ŚWIĄTECZNA LOTERIA TYMBARK DAJ COŚ OD SIEBIE');
INSERT INTO contestsdb.contests (id, accepted,contest_link, description, end_date, image, organizer, reward_description, rules_link, short_description, start_date, title) VALUES (10,true, 'https://www.loteria.dajcosodsiebie.pl/#zasady', '1. Kup dowolne produkty Tymbark za minimum 6 zł spośród soków, nektarów i napojów od 0,2l do 0,3l) i zachowaj paragon', '2018-12-30 22:59:00', '/upload-dir/HzSLTMsm-pantenec4.jpg', 'Tymark', '– 1x samochód Toyota C-HR – 210x bon podarunkowy YES o wartości 200 zł (codziennie 5 nagród)', 'https://www.loteria.dajcosodsiebie.pl/regulaminy/Regulamin%20loterii%20Tymbark.pdf', 'Do wygrania Toyota C-HR oraz bony upominkowe YES o wartości 200 zł!', '2018-11-18 23:00:00', 'ŚWIĄTECZNA LOTERIA TYMBARK DAJ COŚ OD SIEBIE');
INSERT INTO contestsdb.contests (id, accepted,contest_link, description, end_date, image, organizer, reward_description, rules_link, short_description, start_date, title) VALUES (11,true, 'https://www.loteria.dajcosodsiebie.pl/#zasady', '1. Kup dowolne produkty Tymbark za minimum 6 zł spośród soków, nektarów i napojów od 0,2l do 0,3l) i zachowaj paragon', '2018-12-30 22:59:00', '/upload-dir/wLH4qu08-topazgwiazdka.jpg', 'Tymark', '– 1x samochód Toyota C-HR – 210x bon podarunkowy YES o wartości 200 zł (codziennie 5 nagród)', 'https://www.loteria.dajcosodsiebie.pl/regulaminy/Regulamin%20loterii%20Tymbark.pdf', 'Do wygrania Toyota C-HR oraz bony upominkowe YES o wartości 200 zł!', '2018-11-18 23:00:00', 'ŚWIĄTECZNA LOTERIA TYMBARK DAJ COŚ OD SIEBIE');
INSERT INTO contestsdb.contests (id, accepted,contest_link, description, end_date, image, organizer, reward_description, rules_link, short_description, start_date, title) VALUES (12, true,'https://www.loteria.dajcosodsiebie.pl/#zasady', '1. Kup dowolne produkty Tymbark za minimum 6 zł spośród soków, nektarów i napojów od 0,2l do 0,3l) i zachowaj paragon', '2018-12-30 22:59:00', '/upload-dir/Y0RtwEkE-bakallanditm.jpg', 'Tymark', '– 1x samochód Toyota C-HR – 210x bon podarunkowy YES o wartości 200 zł (codziennie 5 nagród)', 'https://www.loteria.dajcosodsiebie.pl/regulaminy/Regulamin%20loterii%20Tymbark.pdf', 'Do wygrania Toyota C-HR oraz bony upominkowe YES o wartości 200 zł!', '2018-11-18 23:00:00', 'ŚWIĄTECZNA LOTERIA TYMBARK DAJ COŚ OD SIEBIE');

INSERT INTO contestsdb.contests_categories (contests_id, categories_id) VALUES (1, 2);
INSERT INTO contestsdb.contests_categories (contests_id, categories_id) VALUES (1, 3);
INSERT INTO contestsdb.contests_categories (contests_id, categories_id) VALUES (1, 4);